### ISSUE TITLE
Create basic drive

### ISSUE THREAD

**Issue by sevenbitscience** [SLHS-Robotics/SLHS-Offseason-2024#3]
Make some basic controls that can drive the robot forwards and backward, as well as rotating to turn left and right

**Comment by sevenbitscience** [comment]
## Basics of Tele-Op control

Control will happen within the `while (opModeIsActive())` loop

### Moving stuff

Servos move when you call the `setPosition`, and motors move when you call the `setPower`

Both of those functions take a double (decimal number) as input

### Getting input

FTC SDK provides two variable for input from the gamepads

`gamepad1` and `gamepad2`

You get input from the user from variables inside of those things

We can get:
- the buttons (a,b,x,y) --> these are bools
- joystick ([left,right]_stick_[x,y]) --> these are doubles
- The triggers --> these are doubles
- The bumpers --> these are bools

You get one of these values by calling something like this

```
gamepad1.a
```

If you keep track of how the inputs are changing over time, you can do edge detection

### Control

You can use logic stuff to control how you move the stuff based on what input you are getting

You probably want to make sure that when you're pressing nothing, the stuff is not moving

**Comment by darthchicken4** [comment]
I created some basic stuff, probably needs heavy adjusting. When Joey is back I think he'll help review code and then I can commit it.

**Comment by sevenbitscience** [comment]
You could commit it to your branch, I can probably take a look sometime tonight (till like 2 AM your time)

**Comment by darthchicken4** [comment]
Oh my bad, didn't see this till now 😅😅

**Comment by darthchicken4** [comment]
I found some things to revise and I am going to rewrite some of it

**Comment by darthchicken4** [comment]
I think I committed it, let me know if it didn't work

**Comment by sevenbitscience** [comment]
We tested the drive, and it needs some improvements.
The first change is that it currently rotates in the opposite direction that we want it.
It also currently does not have any speed control, so we would like to add that.
It could also be beneficial to improve the control flow for the driving code.
